CREATE TABLE usuario (
    id SERIAL PRIMARY KEY,
    user_name VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE autor (
    id SERIAL PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE libro (
    id SERIAL PRIMARY KEY,
    isbn VARCHAR UNIQUE NOT NULL,
    title VARCHAR NOT NULL,
    autor_id INTEGER REFERENCES autor,
    year INTEGER NOT NULL
);

CREATE TABLE review (
    id SERIAL PRIMARY KEY,
    detail VARCHAR NOT NULL,
    stars INTEGER NOT NULL,
    libro_id INTEGER REFERENCES libro,
    usuario_id INTEGER REFERENCES usuario
);
